### ISSUE TITLE
add translate menu to splash by default, and move to map as button when window is closed

### ISSUE THREAD

**Issue by cmenedes** [timkeane/nyc-lib#33]
# Current Behavior
To make our splash window more responsive, we've decided to have it go full-screen on smaller screens. This leaves out the ability to click on the translate button upon page load. 

# Expected Behavior
The user should be able to translate to different languages upon page load, regardless of the splash screen showing or not.

# Failure Information (for bugs)

## Steps to Reproduce
1. Open finderapp.html located in the examples/ol folder
2. Provide splashOptions to the FinderApp constructor: `splashOptions:` {message: 'splash page message'}`
3. Build nyc-lib as described in readme, navigate to dist/examples/ol/finderapp.html
4. Observe if you can translate. Test on smaller screens.

# Proposed Solution
The proposed solution is to add the translate menu to the list of dialog buttons on the splash screen (by default the 'Screen Reader Instructions' & 'Continue' buttons are included). Once the user closes the splash screen, the translate button should appear as a button on the map (as it usually does). If there is no splash screen enabled, the button should still appear on the map.

**Comment by timkeane** [comment]
fixed in commit 62d96a67aef2085a5d523e2d4d7dbe0c2732a731
